services:
    kafka:
      image: confluentinc/cp-kafka:7.9.1
      networks:
        - kafka_net
      ports:
        - "9094:9094"
      volumes:
        - "kafka_data:/confluent"
      environment:
        KAFKA_KRAFT_MODE: "true"
        KAFKA_PROCESS_ROLES: controller,broker
        KAFKA_NODE_ID: 1  
        KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
        ALLOW_PLAINTEXT_LISTENER: yes
        KAFKA_LISTENERS : CLIENT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        KAFKA_ADVERTISED_LISTENERS : CLIENT://kafka:9092,EXTERNAL://localhost:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME : CLIENT
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        CLUSTER_ID: "9YoavaRpTCOitT3Dm2OQFQ"       
        
    kafka-ui:
      image: provectuslabs/kafka-ui:v0.7.0
      networks:
        - kafka_net
      ports:
        - "8088:8080"
      depends_on:
        kafka:
          condition: service_started
        kafka-schema-registry:
          condition: service_started
      environment:
        KAFKA_CLUSTERS_0_NAME: voylaf
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://kafka-schema-registry:8081
        DYNAMIC_CONFIG_ENABLED: 'true'
        
    kafka-schema-registry:
      image: confluentinc/cp-schema-registry:7.9.1
      networks:
        - kafka_net
      ports:
        - "8081:8081"
      depends_on:
        kafka:
          condition: service_started
      environment:
        SCHEMA_REGISTRY_DEBUG: true
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        
        
    prometheus:
      image: prom/prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      networks:
        - kafka_net
        
    grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      networks:
        - kafka_net
      volumes:
        - grafana-storage:/var/lib/grafana    
    
networks:
  kafka_net:
    driver: bridge
    
volumes:
  kafka_data:
  grafana-storage:
        