global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'consumer'
    static_configs:
      - targets: ['localhost:8091']

  - job_name: 'producer'
    static_configs:
      - targets: ['localhost:8092']